spring:
  liquibase:
    change-log: classpath:master.yml
  application:
    api-prefix: /api/v1
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  data:
    web:
      pageable:
        default-page-size: 15
management:
  endpoints:
    web:
      exposure:
        include: '*'