spring:
  liquibase:
    change-log: classpath:master.yml
  application:
    api-prefix: /api/v1
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
management:
  endpoints:
    web:
      exposure:
        include: '*'